export const PAGE_DATA = {
  longTermCareNurse: {
    title: "Nurse at Home",
    tagline: "Apollo nurse at home — skilled nursing care for post-operative recovery, chronic conditions, and daily medical support at home.",
    description: "Skilled nursing care for post-operative recovery, chronic conditions, and daily medical support at home.",
    icon: "stethoscope",
    bg: "ivory",
    priceFrom: "Enquire Now",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "Apollo serves as a bridge between professional medical care and the comfort of one's home, ensuring that patients receive compassionate, personalised, and reliable care tailored to their needs.",
    whoItsFor: [
      "Patients recovering from surgery or illness",
      "Chronic conditions that require ongoing care",
      "Elderly family members who need assistance with daily activities",
      "Families who want professional yet heartfelt care for their seriously ill loved ones",
    ],
    whatsIncluded: [
      "Post-surgical care",
      "Chronic disease management",
      "Elderly care",
      "Paediatric care",
      "Palliative support",
      "Medication administration and monitoring",
    ],
    howItWorks: [
      "Contact Apollo Homecare via phone, email, or website",
      "Share the patient's condition and needs",
      "Apollo matches a trained, verified nurse",
      "Care begins at home on the agreed schedule",
    ],
    related: ["attendant-at-home", "icu-at-home", "elder-care", "ryles-tube-insertion", "foley-catheter-care", "iv-infusion-at-home", "wound-dressing-at-home"],
  },
  longTermCareAttendant: {
    title: "Attendant at Home",
    tagline: "A professional caregiver for non-medical support — bathing, dressing, feeding, mobility, and a clean, safe environment.",
    description: "Professional caregiver for non-medical support — bathing, dressing, feeding, mobility, and a clean, safe environment.",
    icon: "hand-heart",
    bg: "ivory",
    priceFrom: "Pricing on enquiry",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "A trained attendant at home is a professional caregiver who provides non-medical support to patients in the comfort of their homes — assisting with daily activities such as bathing, dressing, feeding, and mobility support, while following specific care plans tailored to the patient's needs.",
    whoItsFor: [
      "Elderly individuals who have difficulty moving around or performing basic activities",
      "Patients recovering from surgery, injuries, or serious illnesses",
      "People with chronic conditions such as Parkinson's, dementia, or paralysis",
      "Bedridden patients who need positioning, feeding, and personal care",
      "Families with busy schedules who cannot provide full-time care",
    ],
    whatsIncluded: [
      "Assistance with bathing, dressing, feeding, and mobility support",
      "Maintaining personal hygiene",
      "Administering prescribed medications",
      "Ensuring a clean and safe environment for the patient",
      "Unlike nurses, trained attendants do not perform medical procedures",
    ],
    howItWorks: [
      "Get in touch with Apollo Homecare by visiting a nearest Apollo hospital, their customer service hotline, or the website",
      "Based on needs and the patient's condition, the team suggests a qualified caregiver",
      "A consultation with medical specialists may be scheduled to ascertain the degree of care required",
      "The patient is allocated to the trained attendant, who starts helping at home",
      "Flexible service options: hourly, daily, and long-term care plans",
    ],
    related: ["nurse-at-home", "elder-care", "post-surgical-care"],
  },
  longTermCareICU: {
    title: "ICU at Home",
    tagline: "Expert critical care in the comfort of your home, with hospital-grade equipment and trained staff.",
    description: "Expert critical care in the comfort of your home, with hospital-grade equipment and trained staff.",
    icon: "monitor-heart",
    bg: "ivory",
    priceFrom: "Pricing on enquiry",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "What is ICU at Home?",
      "Who needs ICU at Home services?",
      "What medical equipment is included in ICU at Home?",
      "What type of medical staff will be available?",
      "Can you manage patients on a ventilator at home?",
      "What if there's a medical emergency at home?",
      "Are medicines and consumables included in the service?",
    ],
    overview: "ICU at home is a facility where a family member who is ill or in a critical situation can get hospital-like treatment at home. These setups include state-of-the-art medical equipment like ventilators, monitors, and infusion pumps, provided by high-quality professionals in the home environment.",
    whoItsFor: [
      "Recovery after hospitalisation — patients who need long-term care after being discharged",
      "Chronic conditions that require constant monitoring",
      "Palliative care — comfort and care for critically ill patients",
      "Infeciton control — reducing the risk of hospital-acquired infections",
      "Patient preference — avoiding long-term hospital stays",
    ],
    whatsIncluded: [
      "Advanced equipment: ventilators, oxygen concentrators, defibrillators, patient monitors, and more",
      "Skilled medical staff: certified nurses and doctors trained in critical care management",
      "24/7 monitoring to ensure patient safety and timely intervention",
      "Customised care plans based on your needs and preferences",
      "Emergency support with quick response in case of complications",
    ],
    howItWorks: [
      "Enquire about ICU at Home",
      "Apollo discusses the patient's condition and requirements",
      "A customised care plan and equipment setup are arranged",
      "The care team begins round-the-clock care at home",
    ],
    related: ["nurse-at-home", "tracheostomy-care"],
  },
  longTermCareElder: {
    title: "Elder Care",
    tagline: "A customised healthcare and support plan for elderly loved ones, on a convenient subscription.",
    description: "Customised healthcare and support plan for elderly loved ones, on a convenient subscription.",
    icon: "users",
    bg: "ivory",
    priceFrom: "Subscription plans: Basic, Advanced Medical (Recommended), and Premium",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "What is a full body checkup?",
      "Can the checkup be done at home?",
      "Which package should I choose?",
    ],
    overview: "Apollo Elder Care Subscription is a customised healthcare and support plan specially designed for elderly individuals to ensure their well-being and comfort at home. It provides continuous professional care, personalised attention, and essential services on a subscription basis.",
    whoItsFor: [
      "Elderly individuals living alone who need assistance with daily tasks",
      "Seniors recovering from surgery or illness who require post-hospital care",
      "Families unable to provide constant care due to work or distance",
      "Seniors with chronic conditions requiring regular health monitoring",
    ],
    whatsIncluded: [
      "Professional medical support: regular health monitoring, vitals, medication management",
      "Assistance with chronic condition management (diabetes, hypertension, arthritis, etc.)",
      "Access to on-call doctors, nurses, and physiotherapists",
      "Personalised care plans with tailored routines and exercise programs",
      "Assistance with daily activities: hygiene, grooming, dressing, feeding, mobility, meals",
      "Emergency support: 24/7 availability of trained caregivers, hospital and ambulance coordination",
      "Companionship and emotional support to reduce loneliness",
    ],
    howItWorks: [
      "Initial assessment — a detailed evaluation of the elderly person's health and lifestyle",
      "Care plan design — a customised subscription plan tailored to individual needs",
      "Service delivery — regular visits by caregivers, nurses, or therapists as per the plan",
      "Monitoring and feedback — periodic reviews to adjust the care plan as needed",
    ],
    related: ["attendant-at-home", "nurse-at-home", "physiotherapy-at-home"],
  },
  homeVisitDoctor: {
    title: "Doctor at Home",
    tagline: "Apollo Doctor at Home — expert medical care at your doorstep, ensuring convenience, comfort, and peace of mind.",
    description: "Expert medical care at your doorstep, ensuring convenience, comfort, and peace of mind.",
    icon: "user-round",
    bg: "ivory",
    priceFrom: 1000,
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "Apollo Home Care's Doctor at Home Service brings expert medical care to your doorstep. Our skilled doctors provide routine checkups, acute care, post-operative support, elderly care, and palliative care — tailored to your unique needs.",
    whoItsFor: [
      "Patients with mobility challenges who find travel difficult",
      "People with chronic conditions needing timely attention",
      "Anyone preferring high-quality medical care at home",
    ],
    whatsIncluded: [
      "Tele Consultation at ₹1,000 — quality healthcare on call",
      "General Practitioners — comprehensive care for all health needs",
      "Specialised Doctor at Home — targeted expertise for complicated medical issues",
    ],
    howItWorks: [
      "Book your Apollo Doctor at home appointment",
      "Choose tele consultation or a home visit",
      "A doctor provides care at the scheduled time",
      "Prescription and follow-up support follow",
    ],
    related: ["physiotherapy-at-home", "post-surgical-care"],
  },
  homeVisitPhysio: {
    title: "Physiotherapy at Home",
    tagline: "Apollo physiotherapists deliver expert care at home to enhance mobility and improve quality of life.",
    description: "Apollo physiotherapists deliver expert care at home to enhance mobility and improve quality of life.",
    icon: "activity",
    bg: "ivory",
    priceFrom: "Pack options: 7, 14, and 30 days",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "Our Apollo physiotherapists deliver expert care at home to enhance mobility and improve quality of life. Collaborating with your doctor and Homecare nurses, they address challenges from illness, injury, disability, or aging — all in the comfort and safety of your home.",
    whoItsFor: [
      "Recovery from injuries, surgeries, or chronic conditions",
      "Mobility and balance concerns",
      "Chronic pain management",
      "Sports injury rehabilitation",
      "Chest and respiratory rehabilitation",
      "Disc-related pain relief",
    ],
    whatsIncluded: [
      "Physiotherapist 14 Days Pack — enhance mobility, healing, and well-being",
      "Physiotherapist 30 Days Pack — healing, mobility, and well-being",
      "Physiotherapist 7 Days Pack — mobility, healing, and well-being",
      "Chest Physiotherapy at home",
      "Sports Physiotherapy — sports injury rehab and performance therapy",
      "Disc Physiotherapy — personalised disc pain relief and recovery exercises",
    ],
    howItWorks: [
      "Enquire with your preferred pack or therapy",
      "A physiotherapist assesses your needs",
      "A personalised rehabilitation program begins at home",
      "Progress is tracked across sessions",
    ],
    related: ["doctor-at-home", "post-surgical-care", "elder-care"],
  },
  homeVisitPostSurgical: {
    title: "Post-Surgical Care",
    tagline: "Structured recovery support after surgery — nursing visits, wound care, and rehabilitation at home.",
    description: "Structured recovery support after surgery — nursing visits, wound care, and rehabilitation at home.",
    icon: "bandage",
    bg: "ivory",
    priceFrom: "Pricing on enquiry",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "Post-surgical care at home helps patients recovering from surgery, injury, or illness receive skilled care without hospital stays. Apollo nurses assist with wound care, medication, and daily recovery needs, enabling quicker recovery in familiar surroundings.",
    whoItsFor: [
      "Patients recovering from surgery who require skilled care at home",
      "Recovery after hospitalisation, including post-operative wound care",
      "Patients needing rehabilitation support after injury or illness",
    ],
    whatsIncluded: [
      "Skilled nursing visits for post-surgical care",
      "Wound dressing and wound care",
      "Medication administration and monitoring",
      "Mobility support and physiotherapy coordination",
      "Recovery monitoring with family updates",
    ],
    howItWorks: [
      "Enquire about post-surgical care",
      "Apollo assesses the recovery needs",
      "A care plan with nursing visits begins at home",
      "Recovery progress is monitored and adjusted",
    ],
    related: ["nurse-at-home", "physiotherapy-at-home", "wound-dressing-at-home"],
  },
  rylesTube: {
    title: "Ryle's Tube Insertion",
    tagline: "Ryle's tube insertion provides feeding, medication, and drainage via a nasal tube.",
    description: "Ryle's tube insertion provides feeding, medication, and drainage via a nasal tube.",
    icon: "syringe",
    bg: "ivory",
    priceFrom: 1500,
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "A flexible tube is inserted into the stomach through the nose during Ryle's tube insertion, often referred to as nasogastric (NG) tube insertion. In patients who are unable to eat or drink normally, it is frequently used for feeding, drug administration, and stomach contents drainage.",
    whoItsFor: [
      "Patients who are unable to eat or drink normally",
      "Bedridden or elderly patients who would otherwise require hospital visits",
    ],
    whatsIncluded: [
      "Safe, precise tube insertion by Apollo's trained nurses with minimal discomfort",
      "Strict sterilisation protocols to prevent infections",
      "Guidance on appropriate feeding schedules and nutrition plans",
      "Regular checks to ensure the tube remains functional",
    ],
    howItWorks: [
      "Book the procedure and check availability at your doorstep",
      "Select your preferred date and slot",
      "A trained nurse performs the procedure at home",
      "Feeding and care guidance is shared with the family",
      "Final confirmation is subject to availability",
    ],
    related: ["nurse-at-home", "iv-infusion-at-home"],
  },
  foleyCatheter: {
    title: "Foley Catheter Insertion",
    tagline: "Foley catheter insertion ensures proper urinary management with secure placement.",
    description: "Foley catheter insertion ensures proper urinary management with secure placement.",
    icon: "syringe",
    bg: "ivory",
    priceFrom: 2200,
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "A thin, flexible tube called a Foley catheter is inserted into the bladder to drain urine. A tiny, inflated balloon holds the catheter in place. Urinary management, either short-term or long-term, is frequently accomplished with this treatment.",
    whoItsFor: [
      "Patients needing relief from urinary retention",
      "Healing after surgeries affecting the urinary tract",
      "Managing incontinence in patients with limited mobility",
      "Monitoring and measuring urine output for medical assessments",
    ],
    whatsIncluded: [
      "Secure, hygienic Foley catheter insertion by trained nurses",
      "A safe, hygienic, and compassionate approach prioritising patient comfort",
      "Catheter care guidance for the family",
      "Consumables at MRP, billed separately",
    ],
    howItWorks: [
      "Book the procedure and check availability at your doorstep",
      "Select your preferred date and slot",
      "A trained nurse performs the procedure at home",
      "Care instructions are shared",
      "Final confirmation is subject to availability",
    ],
    related: ["nurse-at-home", "wound-dressing-at-home"],
  },
  ivInfusion: {
    title: "IV Infusion at Home",
    tagline: "IV infusion with pre-inserted cannula — fluids, drugs, or nutrients delivered at home.",
    description: "IV infusion with pre-inserted cannula — fluids, drugs, or nutrients delivered at home.",
    icon: "droplets",
    bg: "ivory",
    priceFrom: 1500,
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "IV infusion with a cannula already in place uses an intravenous line already inserted into the patient's vein to provide fluids, drugs, or nutrients. The procedure is speedier and less intrusive because the cannula is already installed and the needle doesn't need to be reinserted.",
    whoItsFor: ["Patients who need frequent or ongoing IV therapy"],
    whatsIncluded: [
      "IV infusion with pre-inserted cannula",
      "Minimised discomfort — no needle reinsertion",
      "Reduced preparation time compared to fresh cannulation",
      "Consumables at MRP, billed separately",
    ],
    howItWorks: [
      "Book the procedure and check availability at your doorstep",
      "Select your preferred date and slot",
      "A trained nurse administers the infusion at home",
      "Monitoring continues through the infusion",
      "Final confirmation is subject to availability",
    ],
    related: ["nurse-at-home", "ryles-tube-insertion"],
  },
  woundDressing: {
    title: "Wound Dressing at Home",
    tagline: "Wound dressing promotes healing and prevents infection with sterile materials.",
    description: "Wound dressing promotes healing and prevents infection with sterile materials.",
    icon: "bandage",
    bg: "ivory",
    priceFrom: "Pricing on enquiry",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "Why get nursing procedures done at home?",
      "Are consumables charged separately?",
    ],
    overview: "The process of cleansing, shielding, and covering a wound to encourage healing and ward off infection is known as wound dressing. It entails covering the wound with sterile materials like bandages, gauze, or sophisticated dressings, depending on the size, depth, and state of the wound.",
    whoItsFor: [
      "Cuts, surgical incisions, burns, ulcers, or chronic wounds",
      "Post-surgical patients needing regular dressing changes",
    ],
    whatsIncluded: [
      "Sterile wound cleansing and dressing by trained nurses",
      "Dressings matched to wound type and condition",
      "Infection prevention protocols",
      "Consumables at MRP, billed separately",
    ],
    howItWorks: [
      "Enquire about wound dressing",
      "A trained nurse confirms the visit",
      "The wound is cleansed and dressed at home",
      "Next dressing is scheduled as needed",
    ],
    related: ["post-surgical-care", "nurse-at-home", "foley-catheter-care"],
  },
  tracheostomyCare: {
    title: "Tracheostomy Care",
    tagline: "Skilled care for tracheostomy patients at home — tube care, suctioning, and family training.",
    description: "Skilled care for tracheostomy patients at home — tube care, suctioning, and family training.",
    icon: "wind",
    bg: "ivory",
    priceFrom: "Pricing on enquiry",
    localKeywords: ["Hyderabad", "Chennai", "Bangalore", "Delhi NCR", "Kolkata"],
    faqs: [
      "What is tracheostomy care?",
      "How is quality of care ensured?",
    ],
    overview: "Tracheostomy care at home is provided by Apollo's trained nurses as part of skilled long-term care, supporting patients with airway management needs and training families on safe daily care.",
    whoItsFor: [
      "Patients with tracheostomy or ventilator-related care needs",
      "Families needing daily care guidance for a tracheostomy patient",
    ],
    whatsIncluded: [
      "Skilled nursing care for airway management",
      "Hygienic care following strict protocols",
      "Family training for daily care and safety",
      "Coordination with the care team for emergencies",
    ],
    howItWorks: [
      "Enquire about tracheostomy care",
      "Apollo assesses the patient's needs",
      "A trained nurse provides care at home",
      "Family is trained for daily management",
    ],
    related: ["icu-at-home", "nurse-at-home"],
  },
};

// This file lives under pages/ for co-location; it is a data module, not a route.
export default function CareServicesData() { return null; }
